
package com.ecommerce.features.auth

import com.auth0.jwt.JWT
import com.auth0.jwt.algorithms.Algorithm
import com.ecommerce.features.auth.models.User
import com.ecommerce.features.auth.models.UserLoginRequest
import com.ecommerce.features.auth.models.UserRegistrationRequest
import org.mindrot.jbcrypt.BCrypt
import java.util.*

class AuthService(private val userRepository: UserRepository) {

    suspend fun registerUser(request: UserRegistrationRequest): User {
        val hashedPassword = BCrypt.hashpw(request.password, BCrypt.gensalt())
        val user = User(
            id = 0, // Will be generated by the database
            firstName = request.firstName,
            lastName = request.lastName,
            email = request.email,
            mobile = request.mobile,
            passwordHash = hashedPassword
        )
        return userRepository.createUser(user)
    }

    suspend fun login(request: UserLoginRequest): String? {
        val user = userRepository.getUserByEmail(request.email)
        if (user != null && BCrypt.checkpw(request.password, user.passwordHash)) {
            return generateToken(user)
        }
        return null
    }

    private fun generateToken(user: User): String {
        val secret = "secret" //  TODO: Move to config
        val algorithm = Algorithm.HMAC256(secret)
        val issuer = "http://0.0.0.0:8080/" // TODO: Move to config
        return JWT.create()
            .withAudience("users")
            .withIssuer(issuer)
            .withClaim("userId", user.id)
            .withExpiresAt(Date(System.currentTimeMillis() + 600000)) // 10 minutes
            .sign(algorithm)
    }
}
